### ISSUE TITLE
ModuleNotFoundError: No module named 'video'

### ISSUE THREAD

**Issue by skywo1f** [nrupatunga/PY-GOTURN#26]
/neural-networks/PY-GOTURN$ ./show_tracker_vot.sh 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/neural-networks/PY-GOTURN/goturn/test/show_tracker_vot.py", line 10, in <module>
    from ..loader.loader_vot import loader_vot
  File "neural-networks/PY-GOTURN/goturn/loader/loader_vot.py", line 9, in <module>
    from video import video

**Comment by ykchong45** [comment]
I guess you are using python3 from your error log. Hope [this](https://stackoverflow.com/a/4142178/10566022) post on import is helpful. 

What you can try is to change the line in error to `from .video import video` (adding a dot in front of the first "video").
